version: '3.8'

services:
  db:
    image: neo4j:5.19
    environment:
      NEO4J_AUTH: neo4j/12345678
    ports:
      - "7474:7474"  # Web UI
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    depends_on:
      - bd

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  neo4j_data:
