version: '3.8'

services:
  db:
    image: neo4j:5.19.0  # Указан конкретный тег
    environment:
      NEO4J_AUTH: neo4j/12345678
    volumes:
      - neo4j_data:/data
    # Порты не пробрасываются наружу

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - backend

volumes:
  neo4j_data:
